import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Expoler',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="px-10 pt-5 text-center">
          <Link prefetch href={'/'} className="text-2xl font-semibold">
            Movie <span className="text-teal-500">DB</span>
          </Link>
          <div className="pt-5 font-semibold text-xs md:text-base lg:text-lg ">
            © 2023 Dummy Project :{' '}
            <a className="text-neutral-800" href="https://www.linkedin.com/in/nabilazizi/">
              Muhammad Nabil Azizi
            </a>
          </div>
        </nav>
        {children}
        
      </body>
    </html>
  );
}
